#![forbid(unsafe_code)]

pub mod archive;
pub mod archive_extract;
pub mod archive_index;
pub mod archive_lazy;
pub mod archive_writer;
pub mod crt_startup;
pub mod dynamic_provider;
pub mod elf64;
pub mod executable_pipeline;
pub mod executable_writer;
pub mod forced_undefined;
mod gnu_stack;
pub mod image_base;
pub mod input_object;
pub mod layout;
pub mod library_search;
pub mod link_context;
pub mod link_map;
pub mod link_relocations;
pub mod link_symbols;
pub mod linker_input;
pub mod load_segments;
pub mod object_symbols;
pub mod ordered_inputs;
pub mod output_image;
pub mod partial_link;
pub mod permission_layout;
pub mod pie_runtime;
pub mod preload;
mod program_headers;
pub mod provider_closure;
pub mod rela_apply;
pub mod relocated_sections;
pub mod relocations;
pub mod resolve;
mod section_names;
pub mod shared_object;
pub mod static_link;
mod static_link_core;
pub mod symbol_addresses;
pub mod symbol_names;
mod synthetic_ids;
pub mod system_preload;
pub mod tls;
pub mod version_script;
pub mod x86_64_relocations;
