name: Format patch
on:
  push:
    branches:
      - feat/gnu-hash-external-lookup
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all
      - run: git diff --binary > format.patch
      - uses: actions/upload-artifact@v4
        with:
          name: format-patch
          path: format.patch
